apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: iad.ocir.io/fedexoraclecloud/fsc/helloworld:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
      imagePullSecrets:  
      - name: satishocirsecret
